#ifndef CONFIG_H
#define CONFIG_H

#define RENDERER_WIDTH 512
#define RENDERER_HEIGHT 288
#define RENDERER_RAY_OFFSCREEN 2.0f
#define RENDERER_SUN_OFFSCREEN 1.5f
#define RENDERER_SUN_RESOLUTION_X 2048
#define RENDERER_SUN_RESOLUTION_Y 1024
#define MODEL_SIZE 16
#define MODEL_MAX_HEIGHT 32
#define DATABASE_PATH "prototype.sqlite3"
#define PICK_BIAS 0.01f
#define MOVE_SPEED 500.0f

#endif